name: CI-pipeline

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Coveralls GitHub Action
        uses: coverallsapp/github-action@v2.3.4

      - run: npm ci

      - run: npm test  # Suorita Mocha-testit

            

      - run: npm run coverage  # Luo ja lähetä kattavuusraportti Coverallsille

      - uses: coverallsapp/github-action@v2.3.4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}